### ISSUE TITLE
Opacity for color codes

### ISSUE THREAD

**Issue by lukeflo** [JoseMM2002/walltheme#1]
What about opacity for color codes? E.g. `xxxxxxff` for 8-digit Hex code with 100% opacity. Is it possible or planned to add this functionality?

Maybe configurable through a value in the config like:

```toml
opacity_level = 90
```

Could it be implemented with a hash table holding percentage numbers and the needed 2-digit hex code?

**Comment by JoseMM2002** [comment]
Do you need everything on the same opacity or each color with its own opacity?

**Comment by lukeflo** [comment]
Good question :grin:

To make is as configurable as possible, each color would be the correct way. But thats also more coding, I guess.

Personally, I don't **need** it at all, right now. I just asked because `foot` terminal takes 8-digit hex codes for most coloring. And since hex and rgb offers this options it seems like a natural addition to your programm.

**Comment by JoseMM2002** [comment]
Did the update, got a little busy due to Christmas preparations but should be good enough
